#!/usr/bin/env python

import os
import sys

from dir_utils import AutoChangedDir
from krep_subcmds import all_commands
from options import OptionParser, OptionValueError, Values
from topics import ConfigFile, FileUtils, KrepError, Logger


def _global_options(cmd=None):
    global_options = OptionParser(usage='''\
%prog [OPTIONS] subcmd ...

Execute the specified sub-commands, which can be listed with the command
"%prog help"''')

    # File options
    group = global_options.add_option_group('Global file options')
    group.add_option(
        '-w', '--working-dir',
        dest='working_dir', metavar='WORKING_DIR', default=os.getcwd(),
        help='Set the working directory, or current directory would be used. '
             'default: %default')
    group.add_option(
        '--relative-dir',
        dest='relative_dir', metavar='RELATIVE_DIR',
        help='Set the relative directory following working_dir if specified')

    # Debug options
    group = global_options.add_option_group('Global debugging options')
    group.add_option(
        '-T', '--tryrun',
        dest='tryrun', action='store_true', default=False,
        help='try running the command without actual changes to the local '
             'repository and the remote server')
    group.add_option(
        '-v', '--verbose',
        dest='verbose', action='count', default=-1,
        help='set repeatedly to output debug info')

    # Other options
    group = global_options.add_option_group('Global other options')
    group.add_option(
        '--force',
        dest='force', action='store_true', default=False,
        help='force to execute the operations')
    if cmd is None or cmd.support_inject():
        group.add_option(
            '--inject-option',
            dest='inject_option', action='append',
            help='inject implict sub-command options. The format could be '
                 '[cmd:][--]inject-option')

    return global_options


def _get_named_command(name):
    return all_commands.get(name)


def _get_named_options(name):
    _, _, _, optparse = _option_parse([name], Logger.get_logger(name))
    return optparse


def run(name, opts, args, optparse=None, defopts=None, ignore_except=False):  # pylint: disable=R0913
    logger = Logger.get_logger(name)

    lopts = Values(opts)
    try:
        cmd = all_commands[name]
        cmd._run = run  # pylint: disable=W0212
        cmd._cmd = _get_named_command  # pylint: disable=W0212
        cmd._cmdopt = _get_named_options  # pylint: disable=W0212

        logger = Logger.set(
            verbose=lopts.exude('verbose'), name=cmd.get_name(lopts))

        # sub-command
        if optparse is None:
            _, _, _, optparse = _option_parse([name], logger)
            ops, _ = optparse.parse_args([])
            lopts.join(ops, option=optparse)
            optparse.join(lopts)

            # inject options
            for opt in lopts.exude('inject_option') or list():
                if opt.find(':') > 0:
                    oname = opt[:opt.find(':')]
                    if oname in all_commands and oname != name:
                        continue

                if opt.startswith('%s:' % name):
                    opt = opt[len(name) + 1:]
                if not opt.startswith('-'):
                    opt = '--%s' % opt

                try:
                    ops, _ = optparse.parse_args([opt], inject=True)
                    lopts.join(ops, optparse)
                except TypeError:
                    pass

        lopts.join(defopts, optparse, override=False)
        with AutoChangedDir(
            FileUtils.ensure_path(
                lopts.working_dir, lopts.relative_dir, exists=False),
            cleanup=False):
            cmd.execute(lopts, *args)
    except KeyError:
        if ignore_except:
            logger.error('Sub-command is unknown to the program')
        else:
            raise
    except KrepError, e:
        logger.error(e)
    except Exception, e:  # pylint: disable=W0703
        if ignore_except:
            logger.error(e)
        else:
            raise


def _option_parse(argv, logger):
    name = None
    for i in range(len(argv)):
        if not argv[i].startswith('-'):
            name = argv[i]
            del argv[i]
            break

    cmd = None
    if name:
        try:
            cmd = all_commands[name]
            cmd.COMMAND = name
        except KeyError:
            logger.error('Error: Sub-command "%s" is unknown to the program',
                         name)
            sys.exit(1)

        options = cmd.get_option_parser(_global_options(cmd))
    else:
        options = _global_options()

    return name, argv, cmd, options


def main(argv):
    def _loadconf(confname):
        if os.path.exists(confname):
            return ConfigFile(confname).get_default()
        else:
            return Values()

    dopts = Values()
    dopts.join(_loadconf('/etc/default/krepconfig'))
    dopts.join(_loadconf(os.path.expanduser('~/.krepconfig')))

    Logger.set(level=Logger.ERROR, verbose=dopts.verbose)

    logger = Logger.get_logger()
    name, argv, cmd, options = _option_parse(argv, logger)
    try:
        opts, args = options.parse_args(argv)
    except OptionValueError, e:
        options.error(e)
        sys.exit(1)

    # correct the verbose follow the final settings
    verbose = opts.exude('verbose')
    if verbose > -1:
        Logger.set(verbose=verbose)

    if not cmd:
        logger.debug('Exited without sub-command')
        sys.exit(1)

    run(name, opts, args, options, dopts)


if __name__ == '__main__':
    main(sys.argv[1:])
